### PR TITLE
Pointer based functions, tidying up code, distance functions tidied up

### PR DESCRIPTION
**Pull request by 3vcloud**
Modified the Agent and Agent Info sections to use pointers internally to figure a lot of stuff out - avoids having to load whole structs in memory for small loops or tasks.

Location functions were using copy/paste lumps of code to figure stuff like Pseudo location out - I've moved these out to refer to either ComputeDistance or ComputePseudoDistance. Easier to read and update if needed.

Moved away from Directly calling DllStructGetData directly to cater for pointers aswell e.g. GetNearestAgentToCoords now uses GetAgentXY to fetch location info instead of DllStructGetData($struct,'X') and DllStructGetData($struct,'Y') respectively.

Original Agent functions have been modified to accept Pointer based agent arguments instead of just Agent ID or DllStruct objects.

Will be moving on to Items when I have more time.

P.S. Bug with GWA2 Initialize code fixed - it hangs if Initialize(ProcessExists("gw.exe")) is called without the process existing.

### CODE REVIEW

**Comment by 3vcloud** [comment]
I think you mean using pointers in your question, so:

From what I've read up on it (and testing a version of gwAPI that was modified in a similar way to use pointers vs structs) it looks like theres a difference in performance when you use the pointer instead of the struct.

i.e. When you call GetItemByItemID, you first get the pointer for the item, then you use that pointer to build the Dll Struct in memory (which you may not need all of). You can cut out the middle man by just referring to the pointer offset for the value you want, instead of calling DllStructCreate.

You'll only really see a big difference when you're doing stuff like cycling through Agents or Items, but from what I've been testing it looks like a performance improvement.

**Comment by tjubutsi** [comment]
It would add a gigantic code overhead to make functions for every property of every kind of struct we have now though. Instead of doing stuff like GetAgentXY maybe it would be better to make something like GetAgentProperty($agent id/ptr, $property) and then in that function define the offsets and what $property points to what offset.

**Comment by 3vcloud** [comment]
Was thinking that earlier today - will replace with GetAgentProperty and GetItemProperty and you can take another look

**Comment by tjubutsi** [comment]
What would also be nice if you could make a performance comparison, just to actually check if it makes a difference. Something like getting amount of agents in range.

**Comment by 3vcloud** [comment]
Looks like this is only good for the top level iteration - as soon as you want to do something like fetch a model ID, the performance gain is lost and in fact if you want more than that (which you probably would) then it has to build the struct internally via MemoryRead.

Will re-open this pull request when I've tidied up my repo/branched away the pointer stuff for later

**Comment by 3vcloud** [comment]
Added some wait loops to some of the buying/selling/changegold functions to allow the script to pause until the amount or item has been sold/bought etc

GetItemProperty/GetAgentProperty/GetBagProperty can be used in place of DllStructGetData as long as the struct is the default length for that type (e.g. is an agent struct of 448 length and not a custom made one)

Moved the struct string definitions for item, agent and bag to variables at the top of the script.

NOTE: Discussion found [https://www.elitepvpers.com/forum/gw-bot-discussions-questions/4482434-why-address-offset-item-modelid-44-not-42-a.html#post36912775](Here) shows that theres a bug in the Item struct string - I haven't bothered to change it because I was worried it might cause problems turning Interaction from short to long value.

**Comment by tjubutsi** [comment]
With some latest change you did all lines are now changed... Hard to compare D:
I'll have a look sometime soon.

**Comment by 3vcloud** [comment]
OK, going to stop messinng too much with the code base for the next few weeks. Tested and stable, updated version to 4.0.0

**Comment by tjubutsi** [comment]
I'm refactoring a lot of your code right now..

What salvage kit is model 2993?

**Comment by tjubutsi** [comment]
Could you explain how GetItemHasUpgrades works?

**Comment by 3vcloud** [comment]
I think it might be Charr Salvage kit. Let me know if I can help with the refactoring without stepping on toes

**Comment by 3vcloud** [comment]
GetItemHasUpgrades is used as a quick way to tell if an item is likely to have an upgrade. I use this logic in my "IM_SalvageItem" function @ https://github.com/3vcloud/gw_inventorymanager/blob/master/InventoryManager/InventoryManager_Functions.au3 - thought it would be a good idea to put it into GWA2

**Comment by tjubutsi** [comment]
Why all the hassle in LeaveGroup? Just calling the leave group should be enough, even when alone.

**Comment by 3vcloud** [comment]
If you didn't have anyone to leave, the wait loop wouldn't work - would hit the deadlock instead.

**Comment by tjubutsi** [comment]
But why bother even waiting? There's pretty much no use for that.

**Comment by 3vcloud** [comment]
I think you're right, was thinking about issues trying to map away before the SendPacket has worked, but I think Enqueue would make sure that the packets were sent in order?

**Comment by tjubutsi** [comment]
Alright, I made a dev branch for testing on my gitlab https://gitlab.skyweb.nu/skyweb/gwa2/tree/Dev

This is where I'm going to be doing more changes for this PR. I'll do some more changes for item handling (buying kits using model id and changing the buyitem itself thingy)

I think I made all the necessary changes and will be testing this weekend.

Did you ever make a comparison of before and after changes?

**Comment by 3vcloud** [comment]
Ok, will shift over to GL to stay updated.

If there are too many changes for me to keep track of, I use another software package ( https://www.scootersoftware.com/features.php ) to quickly resolve any conflicts between your master and my fork before updating.

**Pull request closed without merging**
